version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    working_directory: ~/activestate/dummy
    docker:
      - image: cimg/ruby:3.4.4-browsers
        environment:
          RAILS_ENV: test

    steps:
      - checkout:
          path: ~/activestate

      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      
      # Restore Cached Dependencies
      - restore_cache:
          keys:
            - bundler-{{ checksum "Gemfile.lock" }}
            - npm-{{ checksum "package-lock.json" }}


      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      
      # Cache Dependencies
      - save_cache:
          paths:
            - vendor/bundle
          key: bundler-{{ checksum "Gemfile.lock" }}

      - run: npm install

      # Install activestate dependencies
      - run: (cd ../package && npm install)

        # Cache Dependencies
      - save_cache:
          paths:
            - ~/.cache/npm
          key: npm-{{ checksum "package-lock.json" }}
        

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake test:system test

      - store_test_results:
          path: test/reports
